### PR TITLE
More Go-like API, docs and a bug fix

### PR DESCRIPTION
**Pull request by gonutz**
I like the idea of a Go wrapper for ffmpeg. I have used this tool in the past a lot and still cannot remember the right parameters. I ended up having a set of batch scripts as a reference. Nice idea, your library has a lot of potential!

I have forked your repo and gradually made some changes to make your code simpler, better to read, more self-contained, more Go-like and in the process changed your public API.

Please have a look at my commits and their messages, I tried to justify the changes in every commit with the message so I omit repeating it all here.

### CODE REVIEW

**Comment by jtguibas** [comment]
Hi! I really appreciate what you did and will look deeply into all the issues you've opened. I've only looked at this new branch for a few minutes so far, but it looks great.

**Comment by gonutz** [comment]
Sure, take your time :-)

**Comment by jtguibas** [comment]
Really good stuff! The refactor and improvement in documentation was very much needed. I definitely agree that Go libraries should try to be dependency-free if possible. It just makes me sad that the Go JSON library requires so many lines of code to just get a few variables–but I think you've made the right choice here.

I'm going to go ahead and merge this pull request. All the tests I ran seemed to work. Closing #3 as a result.

**Comment by jtguibas** [comment]
Thanks for this! Feel free to keep contributing to this project. 😄 

You should look into MoviePy if you often deal with this sort of stuff. It's ultimately what inspired me to make this library–it works a bit differently, though. Instead of having one FFMPEG command that does everything, it actually loads the video into memory using FFMPEG then does all the editing and stuff using the actual raw data.

**Pull request merged**
