### PR TITLE
Fix #5: document behavior of Video.Duration()

### LINKED ISSUE #5: Duration always returns the length of the input video
Calling Trim will not change the result of the Duration function. This might be misleading but is probably what we want. In that case, we should update the doc comment to state that Duration is always the duration of the input video.

### PR DESCRIPTION
**Pull request by gonutz**
Clarify what Duration does instead of changing its implementation. The
doc now gives a hint at how to get the trimmed duration.

### CODE REVIEW

**Comment by jtguibas** [comment]
Looks good to me!

Unfortunately, I've been quite busy and have been unable to keep working on this project. I plan to sometime in the future. Because you seem interested, would you like me to add you as a collaborator (to give you permissions to commit, handle pull requests, etc). I would be more than happy to add you.

**Comment by gonutz** [comment]
Sure, I am changing a few things right now, this would spare me the hassle of creating forks and branches for PRs. Thanks!

**Comment by jtguibas** [comment]
Awesome! Added you :)

**Comment by gonutz** [comment]
Thanks, already pushed my first commit ;-)

**Pull request merged**
